import { createApp } from 'vue';
import App from './app.vue';
import kkElementPlus from 'kk-element-plus';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import 'virtual:uno.css';
const app = createApp(App);
app.use(ElementPlus);
app.use(kkElementPlus);
app.mount('#app');
